from setuptools import setup, find_packages

setup(
    name="crawl4ai-backend",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "fastapi==0.100.0",
        "uvicorn==0.22.0",
        "pydantic==2.0.0",
        "python-multipart==0.0.6",
        "crawl4ai==0.1.0",
        "websockets==11.0.3",
        "python-jose[cryptography]==3.3.0",
        "passlib[bcrypt]==1.7.4",
        "python-dotenv==1.0.0",
        "aiofiles==23.1.0",
        "jinja2==3.1.2",
        "selenium==4.15.0",
        "webdriver-manager==4.0.1",
        "playwright==1.49.0",
        "beautifulsoup4==4.12.2",
        "lxml==5.3.0",
        "pillow==10.4.0",
        "numpy==1.26.0",
        "rich==13.9.4"
    ],
    python_requires=">=3.10",
    author="Your Name",
    author_email="your.email@example.com",
    description="Backend server for Crawl4AI playground",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/crawl4ai",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
) 